### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sajati** [WindySha/ManifestEditor#14]
can it be used to replace screen orientation ? 

i have this line in AndroidManifest.xml :
`<activity android:exported="false" android:name="com.blablabla.Activity" android:screenOrientation="sensorPortrait"/>`
i want to change it to :
`<activity android:exported="false" android:name="com.blablabla.Activity" android:screenOrientation="landscape"/>`

what parameter should i use ?

**Comment by WindySha** [comment]
This is not supported, please add this feature based on this project.
